version: "3.9"

services:
  #  Alice in Wonderland database
  neo4j_alice:
    image: neo4j:5-community
    container_name: neo4j_alice
    environment:
      # credentials
      NEO4J_AUTH: "neo4j/password1"
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
      # plugins
      NEO4J_PLUGINS: '["apoc","graph-data-science"]'
      # allow APOC & GDS stored procedures
      NEO4J_dbms_security_procedures_unrestricted: "apoc.*,gds.*"
      NEO4J_dbms_security_procedures_allowlist:    "apoc.*,gds.*"
    ports:
      - "7475:7474"        # HTTP browser → http://localhost:7475
      - "7686:7687"        # Bolt         → bolt://localhost:7686
    volumes:
      - ./data-alice:/data
      - ./logs-alice:/logs

  #  Dr Jekyll & Mr Hyde database
  neo4j_jekyll:
    image: neo4j:5-community
    container_name: neo4j_jekyll
    environment:
      NEO4J_AUTH: "neo4j/password2"
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
      NEO4J_PLUGINS: '["apoc","graph-data-science"]'
      NEO4J_dbms_security_procedures_unrestricted: "apoc.*,gds.*"
      NEO4J_dbms_security_procedures_allowlist:    "apoc.*,gds.*"
    ports:
      - "7476:7474"        # HTTP browser → http://localhost:7476
      - "7688:7687"        # Bolt         → bolt://localhost:7688
    volumes:
      - ./data-jekyll:/data
      - ./logs-jekyll:/logs
